services:
  laravel-docker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-full-stack
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dfss
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql_db
